# Project
version=0.13.0
group=com.girafi.waddles
java_version=25

# Common
minecraft_version=26.1
mod_name=Waddles
mod_author=Girafi
mod_id=waddles
license=All Rights Reserved
credits=Thanks to Wiiv for making the models!
description=Waddles adds somewhat realistic Adelie penguins that waddle.
minecraft_version_range=[26.1, 26.2)
neo_form_version=26.1-1

# Fabric
fabric_version=0.144.3+26.1
fabric_loader_version=0.18.5

# NeoForge
neoforge_version=26.1.0.5-beta
neoforge_loader_version_range=[4,)
neoforge_version_range=[26.1.0.0,)

# Mod Support
forge_config_api_port=26.1.0.1

# Gradle
org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false
